<?xml version="1.0"?><!DOCTYPE catalog [<!ELEMENT catalog (book) ><!ELEMENT book (author,title,genre,price,publish_date,description)><!ELEMENT author ( #PCDATA ) ><!ELEMENT title ( #PCDATA ) ><!ELEMENT genre ( #PCDATA )><!ELEMENT price ( #PCDATA )><!ELEMENT publish_date ( #PCDATA ) ><!ELEMENT description ( #PCDATA )><!ATTLIST book id ID #IMPLIED><!ATTLIST catalog id ID #IMPLIED >]><catalog id="cat"><book id="bk101"><author id="a1">Gambardella, Matthew</author><title id="t1">XML Developer's Guide</title><genre id="g1">Computer</genre><price id="pq">44.95</price><publish_date id="pd1">2000-10-01</publish_date><description id="d1">An in-depth look at creating applications with XML.</description></book><book id="bk102"><author id="a2">Ralls, Kim</author><title id="t2">Midnight Rain</title><genre id="g2">Fantasy</genre><price id="p2">5.95</price><publish_date id="pd2">2000-12-16</publish_date><description id="d2">A former architect battles corporate zombies,  an evil sorceress, and her own childhood to become queen  of the world.</description></book></catalog> 